### ISSUE TITLE
Interested in using a Rust implementation of Wayland

### ISSUE THREAD

**Issue by danimesq** [roscale/wayvern#1]
What would be the basic steps for replacing the normal Wayland, to this Rust Wayland: https://github.com/Smithay/wayland-rs ?

ping @roscale 🙏

**Comment by roscale** [comment]
I think you can just remove the `use_system_lib` feature from Cargo.toml, and it will choose the wayland implementation written in Rust.

Btw, in case you don't know, all development of this Rust Flutter embedder moved over https://github.com/free-explorers/veshell-prototype/
